### ISSUE TITLE
Mitarbeit an welchem Branch?

### ISSUE THREAD

**Issue by datazuul** [engine-alpha/engine-alpha#15]
Ich würde evtl. gerne an der engine mitarbeiten.
Ich sehe einen 4.x branch, der in Teilen aktueller ist als der main-Branch.

Ist das ein funktionierender Branch, der weiterentwickelt wird?

**Comment by datazuul** [comment]
ich habe gerade gesehen, dass der 4.x branch wohl auf JavaFX basieren sollte, was ja von Oracle wieder gefallen lassen wurde.
Es scheint also besser zu sein, mit dem master-Branch zu beginnen?
(Diesen konnte ich kompilieren und ausführen.)

**Comment by kelunik** [comment]
Der 4.x Branch ist der aktuelle Entwicklungsbranch und basiert auf jbox2d als Physik-Engine. Wo hast du die Referenz zu JavaFX auf dem Branch gefunden?

**Comment by datazuul** [comment]
Es ist nur eine kleine Stelle im Branch 4.x (ich kompiliere mit java 11 ohne FX):

```
import javafx.util.Pair;

@API
public abstract class Joint<JointType extends org.jbox2d.dynamics.joints.Joint> {
  private Pair<JointType, WorldHandler> joint;
```

Falls das nur versehentlich reingerutscht ist (es gäbe in Apache commons auch ein Pair....), dann:

"Branch 4.x" ist dann die Antwort. :+1:
