### ISSUE TITLE
getCenter() Methode der Klasse Bounds

### ISSUE THREAD

**Issue by Josef-Friedrich** [engine-alpha/engine-alpha#43]
Die Dokumentation behauptet durch `x` und `y` würde die linke obere Ecke des Rechtecks angaben.  Die Methode `getCenter()` berechnet jedoch den Mittelpunkt so, als ob mit `x` und `y` die linke untere Ecke des Rechtsecks gemeint ist.

Entweder müsste die Dokumentation der `x` und `y` Eingabeparameter geändert werden oder der Algorithmus in der Methode `getCenter()`.

https://github.com/engine-alpha/engine-alpha/blob/07d7bd9842289849f1ad1082c54e0ecf43ad2473/engine-alpha/src/main/java/ea/internal/Bounds.java#L89-L97

Die Klammer um `width` und `height` sind nicht nötig. Außerdem kann diese Methode mit Gleikommazahlen umgehen. Die Behauptung in der Dokumentation stimmt meiner Meinung nach nicht: `(bei ungeraden Koordinaten mit Abrundung) `

Hier eine kleiner Test:

```java
package ea;

import ea.internal.Bounds;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class BoundsTest {
  @Test
  public void methodGetCenter () {
    Bounds bounds = new Bounds(0, 0, 1, 1);
    Vector vector = bounds.getCenter();
    assertEquals(vector.getX(), 0.5f, 0);
    assertEquals(vector.getY(), 0.5f, 0);
  }
}
```

**Comment by kelunik** [comment]
X und y sind die linke untere Ecke, das hat sich im Rahmen der 4.x Entwicklung geändert, früher war es links oben.

**Comment by Josef-Friedrich** [comment]
https://github.com/engine-alpha/engine-alpha/pull/46
